[package]
name = "ntpscan"
version = "0.1.0"
edition = "2024"
authors = ["Rein Fernhout (LevitatingBusinessMan)"]

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
nix = { version = "0.30.1", features = ["uio", "socket", "net"] }
